// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import entity "github.com/rahman-teja/quiz-master/internal/entity"
import mock "github.com/stretchr/testify/mock"

// AnswersRepository is an autogenerated mock type for the AnswersRepository type
type AnswersRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, questions
func (_m *AnswersRepository) Create(ctx context.Context, questions entity.Answers) error {
	ret := _m.Called(ctx, questions)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Answers) error); ok {
		r0 = rf(ctx, questions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx
func (_m *AnswersRepository) Get(ctx context.Context) ([]entity.Answers, error) {
	ret := _m.Called(ctx)

	var r0 []entity.Answers
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Answers); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Answers)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
