// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import entity "github.com/rahman-teja/quiz-master/internal/entity"
import mock "github.com/stretchr/testify/mock"

// AnswersQueryRepository is an autogenerated mock type for the AnswersQueryRepository type
type AnswersQueryRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx
func (_m *AnswersQueryRepository) Get(ctx context.Context) ([]entity.Answers, error) {
	ret := _m.Called(ctx)

	var r0 []entity.Answers
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Answers); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Answers)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
