// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import entity "github.com/rahman-teja/quiz-master/internal/entity"
import mock "github.com/stretchr/testify/mock"

// AnswersCommandRepository is an autogenerated mock type for the AnswersCommandRepository type
type AnswersCommandRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, questions
func (_m *AnswersCommandRepository) Create(ctx context.Context, questions entity.Answers) error {
	ret := _m.Called(ctx, questions)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Answers) error); ok {
		r0 = rf(ctx, questions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
