// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import entity "github.com/rahman-teja/quiz-master/internal/entity"
import mock "github.com/stretchr/testify/mock"

// QuestionsRepository is an autogenerated mock type for the QuestionsRepository type
type QuestionsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, questions
func (_m *QuestionsRepository) Create(ctx context.Context, questions entity.Questions) error {
	ret := _m.Called(ctx, questions)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Questions) error); ok {
		r0 = rf(ctx, questions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *QuestionsRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx
func (_m *QuestionsRepository) Get(ctx context.Context) ([]entity.Questions, error) {
	ret := _m.Called(ctx)

	var r0 []entity.Questions
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Questions); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Questions)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOne provides a mock function with given fields: ctx, id
func (_m *QuestionsRepository) GetOne(ctx context.Context, id string) (entity.Questions, error) {
	ret := _m.Called(ctx, id)

	var r0 entity.Questions
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Questions); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Questions)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, questions
func (_m *QuestionsRepository) Update(ctx context.Context, id string, questions entity.Questions) error {
	ret := _m.Called(ctx, id, questions)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.Questions) error); ok {
		r0 = rf(ctx, id, questions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
