// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import entity "github.com/rahman-teja/quiz-master/internal/entity"
import mock "github.com/stretchr/testify/mock"
import model "github.com/rahman-teja/quiz-master/internal/model"

// AnswersCommandUsecase is an autogenerated mock type for the AnswersCommandUsecase type
type AnswersCommandUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, payload
func (_m *AnswersCommandUsecase) Create(ctx context.Context, payload model.Answers) (entity.Answers, interface{}, error) {
	ret := _m.Called(ctx, payload)

	var r0 entity.Answers
	if rf, ok := ret.Get(0).(func(context.Context, model.Answers) entity.Answers); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(entity.Answers)
	}

	var r1 interface{}
	if rf, ok := ret.Get(1).(func(context.Context, model.Answers) interface{}); ok {
		r1 = rf(ctx, payload)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(interface{})
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, model.Answers) error); ok {
		r2 = rf(ctx, payload)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
